 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.desktop;

import core.utilities.ComponentResizer;
import core.utilities.Session;
import gui.services.AccountsManagementPanel;
import gui.services.BranchManagementPanel;
import gui.services.DashboardPanel; 
import gui.services.EmployeesManagementPanel;
import gui.services.OccupationsManagementPanel;
import gui.services.ProductManagementPanel;
import gui.services.ServiceManagementPanel; 
import gui.services.SettingsManagementPanel;
import gui.services.TransactionsManagementPanel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author brand
 */
public class DesktopFrame extends javax.swing.JFrame {

    private ServiceManagementPanel servicePanel;
    private ProductManagementPanel productsPanel;
    private TransactionsManagementPanel transactionsPanel;
    private DashboardPanel dashboardPanel;
    private EmployeesManagementPanel employeesPanel;
    private SettingsManagementPanel settings;
    private OccupationsManagementPanel occPanel;
    private AccountsManagementPanel accountPanel;
    private BranchManagementPanel branchPanel;
    
    private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    private boolean fullscreen = false;
    private Session session = new Session();
    
    /**
     * Creates new form DesktopFrame
     */
    public DesktopFrame() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/round-logo.png")).getImage());
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        centerPanel.repaint();
        centerPanel.validate();
        
        servicePanel = new ServiceManagementPanel(session);
        productsPanel = new ProductManagementPanel(session);
        transactionsPanel = new TransactionsManagementPanel(session);
        dashboardPanel = new DashboardPanel(session);
        employeesPanel = new EmployeesManagementPanel(session);
        settings = new SettingsManagementPanel(session);
        occPanel = new OccupationsManagementPanel(session);
        accountPanel = new AccountsManagementPanel(session);
        branchPanel = new BranchManagementPanel(session);
        
        setDefaults();
        setResizableAndMove();
         
    }
    
    public void setResizableAndMove(){
        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        cr.setSnapSize(new Dimension(10, 10));
        cr.setMaximumSize(new Dimension(3840, 2160));
        cr.setMinimumSize(new Dimension(885, 574));
    }
    
    public void setDefaults(){
        
        centerPanel.add(servicePanel);
        servicesBtn.setSelected(true);
        
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(dashboardBtn);
        bg.add(productsBtn);
        bg.add(servicesBtn);
        bg.add(employeesBtn);
        bg.add(transactionsBtn);
        bg.add(settingsBtn);
        bg.add(AccountsBtn);
        bg.add(occupationsBtn);
        bg.add(branchBtn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JToggleButton();
        servicesBtn = new javax.swing.JToggleButton();
        productsBtn = new javax.swing.JToggleButton();
        employeesBtn = new javax.swing.JToggleButton();
        settingsBtn = new javax.swing.JToggleButton();
        transactionsBtn = new javax.swing.JToggleButton();
        occupationsBtn = new javax.swing.JToggleButton();
        AccountsBtn = new javax.swing.JToggleButton();
        branchBtn = new javax.swing.JToggleButton();
        left = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setUndecorated(true);

        main.setBackground(new java.awt.Color(52, 188, 183));
        main.setPreferredSize(new java.awt.Dimension(140, 574));
        main.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        main.add(jLabel1);

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard-pressed.png"))); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        main.add(dashboardBtn);

        servicesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services.png"))); // NOI18N
        servicesBtn.setBorder(null);
        servicesBtn.setBorderPainted(false);
        servicesBtn.setContentAreaFilled(false);
        servicesBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services-pressed.png"))); // NOI18N
        servicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesBtnActionPerformed(evt);
            }
        });
        main.add(servicesBtn);

        productsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products.png"))); // NOI18N
        productsBtn.setBorder(null);
        productsBtn.setBorderPainted(false);
        productsBtn.setContentAreaFilled(false);
        productsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products-pressed.png"))); // NOI18N
        productsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBtnActionPerformed(evt);
            }
        });
        main.add(productsBtn);

        employeesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employees.png"))); // NOI18N
        employeesBtn.setBorder(null);
        employeesBtn.setBorderPainted(false);
        employeesBtn.setContentAreaFilled(false);
        employeesBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employees-pressed.png"))); // NOI18N
        employeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesBtnActionPerformed(evt);
            }
        });
        main.add(employeesBtn);

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings-pressed.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        main.add(settingsBtn);

        transactionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transdaction.png"))); // NOI18N
        transactionsBtn.setBorder(null);
        transactionsBtn.setBorderPainted(false);
        transactionsBtn.setContentAreaFilled(false);
        transactionsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction-pressed.png"))); // NOI18N
        transactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsBtnActionPerformed(evt);
            }
        });
        main.add(transactionsBtn);

        occupationsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/occupations.png"))); // NOI18N
        occupationsBtn.setBorder(null);
        occupationsBtn.setBorderPainted(false);
        occupationsBtn.setContentAreaFilled(false);
        occupationsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/occupations-pressed.png"))); // NOI18N
        occupationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationsBtnActionPerformed(evt);
            }
        });
        main.add(occupationsBtn);

        AccountsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accounts.png"))); // NOI18N
        AccountsBtn.setBorder(null);
        AccountsBtn.setBorderPainted(false);
        AccountsBtn.setContentAreaFilled(false);
        AccountsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accounts-pressed.png"))); // NOI18N
        AccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsBtnActionPerformed(evt);
            }
        });
        main.add(AccountsBtn);

        branchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/branch.png"))); // NOI18N
        branchBtn.setBorder(null);
        branchBtn.setBorderPainted(false);
        branchBtn.setContentAreaFilled(false);
        branchBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/branch-pressed.png"))); // NOI18N
        branchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnActionPerformed(evt);
            }
        });
        main.add(branchBtn);

        getContentPane().add(main, java.awt.BorderLayout.LINE_START);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        left.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(745, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 7));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/size.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        left.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.BorderLayout());
        left.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(left, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof DashboardPanel)){
            centerPanel.removeAll();
            centerPanel.add(dashboardPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void servicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof ServiceManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(servicePanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_servicesBtnActionPerformed

    private void productsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof ProductManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(productsPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_productsBtnActionPerformed

    private void employeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof EmployeesManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(employeesPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_employeesBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof SettingsManagementPanel)){
            settings.refreshBranches();
            centerPanel.removeAll();
            centerPanel.add(settings);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void transactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsBtnActionPerformed
        // TODO add your handling code here:
        
        if(!(centerPanel.getComponent(0) instanceof TransactionsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(transactionsPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_transactionsBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (fullscreen) {
            fullscreen = false;
            setSize(885, 574);
            this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        } else {
            fullscreen = true;
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void occupationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof OccupationsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(occPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_occupationsBtnActionPerformed

    private void AccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof AccountsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(accountPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_AccountsBtnActionPerformed

    private void branchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof BranchManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(branchPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_branchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AccountsBtn;
    private javax.swing.JToggleButton branchBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JToggleButton dashboardBtn;
    private javax.swing.JToggleButton employeesBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel left;
    private javax.swing.JPanel main;
    private javax.swing.JToggleButton occupationsBtn;
    private javax.swing.JToggleButton productsBtn;
    private javax.swing.JToggleButton servicesBtn;
    private javax.swing.JToggleButton settingsBtn;
    private javax.swing.JToggleButton transactionsBtn;
    // End of variables declaration//GEN-END:variables
}
