 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.desktop;

import com.mysql.cj.conf.PropertyKey;
import core.general.Account;
import core.utilities.ComponentResizer;
import core.utilities.Session;
import gui.dialoguePanels.YesNoDialogue;
import gui.services.AccountsManagementPanel;
import gui.services.BranchManagementPanel;
import gui.services.DashboardPanel; 
import gui.services.EmployeesManagementPanel;
import gui.services.OccupationsManagementPanel;
import gui.services.ProductManagementPanel;
import gui.services.ServiceManagementPanel; 
import gui.services.SettingsManagementPanel;
import gui.services.TransactionsManagementPanel;
import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author brand
 */
public class DesktopFrame extends javax.swing.JFrame {

    private ServiceManagementPanel servicePanel;
    private ProductManagementPanel productsPanel;
    private TransactionsManagementPanel transactionsPanel;
    private DashboardPanel dashboardPanel;
    private EmployeesManagementPanel employeesPanel;
    private SettingsManagementPanel settings;
    private OccupationsManagementPanel occPanel;
    private AccountsManagementPanel accountPanel;
    private BranchManagementPanel branchPanel;
    
    private boolean fullscreen = false;
    private Session session;
    private Dimension dim;
    private Account selectedAccount;
    
    /**
     * Creates new form DesktopFrame
     */
    public DesktopFrame(Dimension dim, Session session) {
        
        initComponents();
        this.dim = dim;
        this.session = session;
        this.selectedAccount = session.getLoggedInUser();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/round-logo.png")).getImage());
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        centerPanel.repaint();
        centerPanel.validate();
        
        servicePanel = new ServiceManagementPanel(session);
        productsPanel = new ProductManagementPanel(session);
        transactionsPanel = new TransactionsManagementPanel(session);
        dashboardPanel = new DashboardPanel(session);
        employeesPanel = new EmployeesManagementPanel(session);
        settings = new SettingsManagementPanel(session);
        occPanel = new OccupationsManagementPanel(session);
        accountPanel = new AccountsManagementPanel(session);
        branchPanel = new BranchManagementPanel(session);
        
        setDefaults();
        setResizableAndMove();
        
    } 

    public void setResizableAndMove(){
        ComponentResizer cr = new ComponentResizer();
        cr.registerComponent(this);
        cr.setSnapSize(new Dimension(10, 10));
        cr.setMaximumSize(new Dimension(3840, 2160));
        cr.setMinimumSize(new Dimension(885, 574));
    }
    
    public void setDefaults(){
        centerPanel.add(dashboardPanel);
        dashboardBtn.setSelected(true);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(dashboardBtn);
        bg.add(productsBtn);
        bg.add(servicesBtn);
        bg.add(employeesBtn);
        bg.add(transactionsBtn);
        bg.add(settingsBtn);
        bg.add(AccountsBtn);
        bg.add(occupationsBtn);
        bg.add(branchBtn);
        
        userNameLbl.setText(selectedAccount.getUsername());
        
        AccountsBtn.setVisible(selectedAccount.isAccounts());
        transactionsBtn.setVisible(selectedAccount.isTransactions());
        servicesBtn.setVisible(selectedAccount.isServices());
        productsBtn.setVisible(selectedAccount.isProducts());
        employeesBtn.setVisible(selectedAccount.isEmployees());
        settingsBtn.setVisible(selectedAccount.isSettings());
        
        branchBtn.setVisible((selectedAccount.isAdmin()) ? true : false);
        occupationsBtn.setVisible((selectedAccount.isAdmin()) ? true : false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JToggleButton();
        servicesBtn = new javax.swing.JToggleButton();
        productsBtn = new javax.swing.JToggleButton();
        employeesBtn = new javax.swing.JToggleButton();
        settingsBtn = new javax.swing.JToggleButton();
        transactionsBtn = new javax.swing.JToggleButton();
        occupationsBtn = new javax.swing.JToggleButton();
        AccountsBtn = new javax.swing.JToggleButton();
        branchBtn = new javax.swing.JToggleButton();
        left = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userNameLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        minimizeBtn = new javax.swing.JButton();
        resizeBtn = new javax.swing.JButton();
        closeBtn = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setUndecorated(true);

        main.setBackground(new java.awt.Color(52, 188, 183));
        main.setPreferredSize(new java.awt.Dimension(140, 574));
        main.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        main.add(jLabel1);

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard.png"))); // NOI18N
        dashboardBtn.setBorder(null);
        dashboardBtn.setBorderPainted(false);
        dashboardBtn.setContentAreaFilled(false);
        dashboardBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/dashboard-pressed.png"))); // NOI18N
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        main.add(dashboardBtn);

        servicesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services.png"))); // NOI18N
        servicesBtn.setBorder(null);
        servicesBtn.setBorderPainted(false);
        servicesBtn.setContentAreaFilled(false);
        servicesBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/services-pressed.png"))); // NOI18N
        servicesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicesBtnActionPerformed(evt);
            }
        });
        main.add(servicesBtn);

        productsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products.png"))); // NOI18N
        productsBtn.setBorder(null);
        productsBtn.setBorderPainted(false);
        productsBtn.setContentAreaFilled(false);
        productsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/products-pressed.png"))); // NOI18N
        productsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBtnActionPerformed(evt);
            }
        });
        main.add(productsBtn);

        employeesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employees.png"))); // NOI18N
        employeesBtn.setBorder(null);
        employeesBtn.setBorderPainted(false);
        employeesBtn.setContentAreaFilled(false);
        employeesBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/employees-pressed.png"))); // NOI18N
        employeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesBtnActionPerformed(evt);
            }
        });
        main.add(employeesBtn);

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings-pressed.png"))); // NOI18N
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        main.add(settingsBtn);

        transactionsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transdaction.png"))); // NOI18N
        transactionsBtn.setBorder(null);
        transactionsBtn.setBorderPainted(false);
        transactionsBtn.setContentAreaFilled(false);
        transactionsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transaction-pressed.png"))); // NOI18N
        transactionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionsBtnActionPerformed(evt);
            }
        });
        main.add(transactionsBtn);

        occupationsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/occupations.png"))); // NOI18N
        occupationsBtn.setBorder(null);
        occupationsBtn.setBorderPainted(false);
        occupationsBtn.setContentAreaFilled(false);
        occupationsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/occupations-pressed.png"))); // NOI18N
        occupationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                occupationsBtnActionPerformed(evt);
            }
        });
        main.add(occupationsBtn);

        AccountsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accounts.png"))); // NOI18N
        AccountsBtn.setBorder(null);
        AccountsBtn.setBorderPainted(false);
        AccountsBtn.setContentAreaFilled(false);
        AccountsBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/accounts-pressed.png"))); // NOI18N
        AccountsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsBtnActionPerformed(evt);
            }
        });
        main.add(AccountsBtn);

        branchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/branch.png"))); // NOI18N
        branchBtn.setBorder(null);
        branchBtn.setBorderPainted(false);
        branchBtn.setContentAreaFilled(false);
        branchBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/branch-pressed.png"))); // NOI18N
        branchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchBtnActionPerformed(evt);
            }
        });
        main.add(branchBtn);

        getContentPane().add(main, java.awt.BorderLayout.LINE_START);

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(204, 204, 204)));
        left.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(745, 45));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 7));

        userNameLbl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        userNameLbl.setForeground(new java.awt.Color(153, 153, 153));
        userNameLbl.setText("Brandon Klaas");
        jPanel3.add(userNameLbl);

        jLabel4.setText(" ");
        jPanel3.add(jLabel4);

        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        exitBtn.setBorder(null);
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-pressed.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        jPanel3.add(exitBtn);

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("   |   ");
        jPanel3.add(jLabel2);

        minimizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/minimize.png"))); // NOI18N
        minimizeBtn.setBorder(null);
        minimizeBtn.setBorderPainted(false);
        minimizeBtn.setContentAreaFilled(false);
        minimizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(minimizeBtn);

        resizeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/size.png"))); // NOI18N
        resizeBtn.setBorder(null);
        resizeBtn.setBorderPainted(false);
        resizeBtn.setContentAreaFilled(false);
        resizeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(resizeBtn);

        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        closeBtn.setBorder(null);
        closeBtn.setBorderPainted(false);
        closeBtn.setContentAreaFilled(false);
        closeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(closeBtn);

        left.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setLayout(new java.awt.BorderLayout());
        left.add(centerPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(left, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof DashboardPanel)){
            centerPanel.removeAll();
            dashboardPanel.refreshCards();
            centerPanel.add(dashboardPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void servicesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicesBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof ServiceManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(servicePanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_servicesBtnActionPerformed

    private void productsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof ProductManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(productsPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_productsBtnActionPerformed

    private void employeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof EmployeesManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(employeesPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_employeesBtnActionPerformed

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof SettingsManagementPanel)){
            settings.refreshBranches();
            centerPanel.removeAll();
            centerPanel.add(settings);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void transactionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionsBtnActionPerformed
        // TODO add your handling code here:
        
        if(!(centerPanel.getComponent(0) instanceof TransactionsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(transactionsPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_transactionsBtnActionPerformed

    private void closeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBtnActionPerformed
        // TODO add your handling code here:
        new YesNoDialogue(this, true, "      Are you sure you'd <p> like to close the program?     ", "Exit");
    }//GEN-LAST:event_closeBtnActionPerformed

    public void closeDatabase(){
        session.getDatabase().close();
    }
    
    private void resizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeBtnActionPerformed
        // TODO add your handling code here:
        if (fullscreen) {
            fullscreen = false;
            setSize(885, 574);
            this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        } else {
            fullscreen = true;
            setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_resizeBtnActionPerformed

    private void occupationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_occupationsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof OccupationsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(occPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_occupationsBtnActionPerformed

    private void AccountsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof AccountsManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(accountPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_AccountsBtnActionPerformed

    private void branchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchBtnActionPerformed
        // TODO add your handling code here:
        if(!(centerPanel.getComponent(0) instanceof BranchManagementPanel)){
            centerPanel.removeAll();
            centerPanel.add(branchPanel);
            centerPanel.repaint();
            centerPanel.validate();
        }
    }//GEN-LAST:event_branchBtnActionPerformed

    private void minimizeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeBtnActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        new YesNoDialogue(this, true, "Are you sure you'd like to log out?", "LogOut");
    }//GEN-LAST:event_exitBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AccountsBtn;
    private javax.swing.JToggleButton branchBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton closeBtn;
    private javax.swing.JToggleButton dashboardBtn;
    private javax.swing.JToggleButton employeesBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel left;
    private javax.swing.JPanel main;
    private javax.swing.JButton minimizeBtn;
    private javax.swing.JToggleButton occupationsBtn;
    private javax.swing.JToggleButton productsBtn;
    private javax.swing.JButton resizeBtn;
    private javax.swing.JToggleButton servicesBtn;
    private javax.swing.JToggleButton settingsBtn;
    private javax.swing.JToggleButton transactionsBtn;
    private javax.swing.JLabel userNameLbl;
    // End of variables declaration//GEN-END:variables

}
