/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.desktop;

import core.general.Person;
import core.utilities.Session;
import gui.services.DashboardPanel;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author brand
 */
public class LiveWaitlist extends javax.swing.JFrame {
    
    private ArrayList<Person> waitlist;
    private DashboardPanel panel;
    private Session session;

    /**
     * Creates new form LiveWaitlist
     */
    public LiveWaitlist(Session session, DashboardPanel panel) {
        this.panel = panel;
        this.session = session;
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/round-logo.png")).getImage());
        showOnScreen(1, this);
        this.setVisible(true);
    }
    
    
    public LiveWaitlist(Session session, DashboardPanel panel, ArrayList<Person> waitlist) {
        this.panel = panel;
        this.session = session;
        this.waitlist = waitlist;
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/round-logo.png")).getImage());
        showOnScreen(1, this);
        refresh(waitlist);
        this.setVisible(true);
    }
    
    public void refresh(ArrayList<Person> waitlist){
        this.waitlist = waitlist;
        namesPanel.removeAll();
        
        for(int i = 0; i < waitlist.size(); i++){
            if(i < 16){
                JLabel tmp = new JLabel();
                tmp.setText("  "+(i+1)+" - "+waitlist.get(i).getFirstname()+" "+waitlist.get(i).getLastname());
                tmp.setFont(new Font("Segoe UI", Font.PLAIN, 47));
                tmp.setForeground(Color.WHITE);
                namesPanel.add(tmp);
            }
        }
        namesPanel.repaint();
        namesPanel.validate();
    }
    
    public static void showOnScreen( int screen, JFrame frame ) {
	GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
	GraphicsDevice[] gs = ge.getScreenDevices();
	
	if(screen > -1 && screen < gs.length) {
	    gs[screen].setFullScreenWindow(frame);
	}else if(gs.length > 0) {
	    gs[0].setFullScreenWindow(frame);
	}else {
	    throw new RuntimeException("No Screens Found");
	}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 25, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Up next");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        namesPanel.setBackground(new java.awt.Color(0, 0, 0));
        namesPanel.setLayout(new java.awt.GridLayout(6, 2));
        getContentPane().add(namesPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel namesPanel;
    // End of variables declaration//GEN-END:variables
}
