/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.desktop;

import com.mysql.cj.conf.PropertyKey;
import core.database.DatabaseAccessObject;
import core.general.Account;
import core.utilities.Session;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author brand
 */
public class LoginFrame extends javax.swing.JFrame {

    private Session session;
    private Account loggedInUserAccount;
    private DatabaseAccessObject database;
    
    private Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        session = new Session();
        this.database = session.getDatabase();
        initComponents();
        setSize(502,652);
        this.setIconImage(new ImageIcon(getClass().getResource("/icons/round-logo.png")).getImage());
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setVisible(true);
        
        this.getRootPane().setDefaultButton(signinBtn);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        usernameTf = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        signinBtn = new javax.swing.JButton();
        errorLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 650));

        bgPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        bgPanel.setLayout(null);

        usernameTf.setBackground(new java.awt.Color(255, 255, 255));
        usernameTf.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameTf.setForeground(new java.awt.Color(102, 102, 102));
        usernameTf.setToolTipText("Username");
        usernameTf.setBorder(null);
        usernameTf.setPreferredSize(new java.awt.Dimension(73, 26));
        usernameTf.setSelectionColor(new java.awt.Color(0, 204, 204));
        usernameTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameTfMouseClicked(evt);
            }
        });
        bgPanel.add(usernameTf);
        usernameTf.setBounds(138, 300, 265, 45);

        passwordTf.setBackground(new java.awt.Color(255, 255, 255));
        passwordTf.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        passwordTf.setForeground(new java.awt.Color(102, 102, 102));
        passwordTf.setToolTipText("Password");
        passwordTf.setBorder(null);
        passwordTf.setOpaque(false);
        passwordTf.setSelectionColor(new java.awt.Color(0, 204, 204));
        passwordTf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTfFocusGained(evt);
            }
        });
        passwordTf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTfMouseClicked(evt);
            }
        });
        bgPanel.add(passwordTf);
        passwordTf.setBounds(140, 380, 265, 45);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit-pressed.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bgPanel.add(jButton1);
        jButton1.setBounds(350, 460, 55, 56);

        signinBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LoginButton.png"))); // NOI18N
        signinBtn.setBorder(null);
        signinBtn.setBorderPainted(false);
        signinBtn.setContentAreaFilled(false);
        signinBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LoginButton-pressed.png"))); // NOI18N
        signinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinBtnActionPerformed(evt);
            }
        });
        bgPanel.add(signinBtn);
        signinBtn.setBounds(92, 460, 238, 56);

        errorLbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 102, 102));
        errorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorLbl.setText("  ");
        bgPanel.add(errorLbl);
        errorLbl.setBounds(101, 260, 300, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Copyright © 2021 PayBuc (PTY) Ltd. All rights reserved");
        bgPanel.add(jLabel3);
        jLabel3.setBounds(60, 600, 380, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Account");
        bgPanel.add(jLabel2);
        jLabel2.setBounds(140, 200, 200, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/loginBG.png"))); // NOI18N
        bgPanel.add(jLabel1);
        jLabel1.setBounds(1, -4, 500, 660);

        getContentPane().add(bgPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void signinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinBtnActionPerformed
        // TODO add your handling code here:
        if(usernameTf.getText().isEmpty() || new String(passwordTf.getPassword()).isEmpty()){
            errorLbl.setText("Enter Username And Password");
        } else if (usernameTf.getText().equals("Admin") && new String(passwordTf.getPassword()).equals("Admin")){
            Account admin = new Account();
            admin.setUsername("Admin");
            admin.setPassword("Admin");
            
            admin.setAdmin(true);
            admin.setGuest(false);
            admin.setTransactions(true);
            admin.setServices(true);
            admin.setProducts(true);
            admin.setEmployees(true);
            admin.setSettings(true);
            admin.setAccounts(true);
                        
            session.setLoggedInUser(admin);
            this.dispose();
            Loading loading = new Loading(null, false, session);
            loading.startThread();
        
        } else if(validateAccount(usernameTf.getText(), new String(passwordTf.getPassword()))){
            session.setLoggedInUser(loggedInUserAccount);
            this.dispose();
            Loading loading = new Loading(null, false, session);
            loading.startThread();
            
        } else {
            errorLbl.setText("Incorrect Username And Password");
        }
        
    }//GEN-LAST:event_signinBtnActionPerformed

    private void passwordTfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTfFocusGained
        // TODO add your handling code here:
//        if(new String(passwordTf.getPassword()).equals("Password"))
    }//GEN-LAST:event_passwordTfFocusGained

    private void passwordTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTfMouseClicked
        // TODO add your handling code here:
        errorLbl.setText("  ");
    }//GEN-LAST:event_passwordTfMouseClicked

    private void usernameTfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameTfMouseClicked
        // TODO add your handling code here:
        errorLbl.setText("  ");
    }//GEN-LAST:event_usernameTfMouseClicked

    public boolean validateAccount(String Username, String Password){
        
        if((loggedInUserAccount = database.getAccount(Username, Password)) != null){
            return true;
        } else {
            return false;
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JButton signinBtn;
    private javax.swing.JTextField usernameTf;
    // End of variables declaration//GEN-END:variables
}
