/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialoguePanels;

import core.database.DatabaseAccessObject;
import core.general.Branch;
import core.utilities.Session;
import gui.services.BranchManagementPanel;
import javax.swing.ButtonGroup;

/**
 *
 * @author brand
 */
public class BranchDialogue extends javax.swing.JPanel {

    private BranchManagementPanel panel;
    private DatabaseAccessObject database;
    private Branch selectedBranch;
    private Session session;
    private Dialogue diag;
    
    /**
     * Creates new form TransactionDialogue
     */
    public BranchDialogue(Session session, BranchManagementPanel panel) {
        this.session = session;
        this.database = session.getDatabase();
        this.panel = panel;
        initComponents();
        setDefaults();
        updateBtn.setVisible(false);
    }
    
    public BranchDialogue(Session session, BranchManagementPanel panel, Branch selectedBranch) {
        this.session = session;
        this.database = session.getDatabase();
        this.selectedBranch = selectedBranch;
        this.panel = panel;
        initComponents();
        fillPanel();
        setDefaults();
        saveBtn.setVisible(false);
    }
    
    private void setDefaults() {
    }
    
    public void fillPanel(){
        branchNameTf.setText(selectedBranch.getName());
        branchCodeTf.setText(selectedBranch.getBranchNo());
        address.setText(selectedBranch.getAddress());
    }
    

    private void clearPanels() {
        branchNameTf.setText("");
        branchCodeTf.setText("");
        address.setText("");
    }
    
    void setDialogue(Dialogue dialogue) {
        diag = dialogue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        branchNameTf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        branchCodeTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Address :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 140, 100, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Branch Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 100, 16);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 40, 600, 10);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Branch");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(28, 16, 280, 16);
        jPanel1.add(branchNameTf);
        branchNameTf.setBounds(150, 60, 270, 24);

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(150, 140, 270, 83);
        jPanel1.add(branchCodeTf);
        branchCodeTf.setBounds(150, 100, 270, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Branch Code :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 110, 100, 16);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(10, 45));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-pressed.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(saveBtn);

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        updateBtn.setBorder(null);
        updateBtn.setBorderPainted(false);
        updateBtn.setContentAreaFilled(false);
        updateBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-pressed.png"))); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(updateBtn);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel-pressed.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelBtn);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:        
        if(branchNameTf.getText().isEmpty() == false && branchCodeTf.getText().isEmpty() == false){
            Branch branch = new Branch();
            branch.setName(branchNameTf.getText());
            branch.setBranchNo(branchCodeTf.getText());
            branch.setAddress(address.getText());
            
            if(database.insert(branch)){
                clearPanels();
                panel.refreshTable();
                diag.setVisible(false);
                new OkayDialogue(null, true, "Branch saved successfully");
                diag.dispose();
            } else {
                new OkayDialogue(null, true, "Failed to save Branch");
            }
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        diag.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(branchNameTf.getText().isEmpty() == false && branchCodeTf.getText().isEmpty() == false){
            Branch branch = new Branch();
            branch.setId(selectedBranch.getId());
            branch.setName(branchNameTf.getText());
            branch.setBranchNo(branchCodeTf.getText());
            branch.setAddress(address.getText());
            
            if(database.update(branch)){
                diag.dispose();
                panel.refreshTable();
                diag.setVisible(false);
                new OkayDialogue(null, true, "Branch updated successfully");
                diag.dispose();
            } else {
                new OkayDialogue(null, true, "Failed to update Branch");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField branchCodeTf;
    private javax.swing.JTextField branchNameTf;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables


}
