/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialoguePanels;

import core.database.DatabaseAccessObject;
import core.general.Service;
import core.utilities.Session;
import gui.services.ServiceManagementPanel;

/**
 *
 * @author brand
 */
public class ServiceDialogue extends javax.swing.JPanel {

    private Session session;
    private Dialogue diag;
    private DatabaseAccessObject database;
    private ServiceManagementPanel panel;
    private Service selectedService;
    
    /**
     * Creates new form TransactionDialogue
     */
    public ServiceDialogue(Session session, ServiceManagementPanel panel) {
        this.session = session;
        this.database = session.getDatabase();
        this.panel = panel;
        initComponents();
        setDefaults();
        updateBtn.setVisible(false);
    }

    public ServiceDialogue(Session session, ServiceManagementPanel panel, Service selectedService) {
        this.session = session;
        this.database = session.getDatabase();
        this.panel = panel;
        this.selectedService = selectedService;
        initComponents();
        setDefaults();
        fillPanel();
        saveBtn.setVisible(false);
    }

    private void setDefaults() {
    }
    
    void setDialogue(Dialogue dialogue) {
        diag = dialogue;
    }
    

    public void clearPanels(){
        serviceTf.setText("");
        descriptionTf.setText("");
        priceTf.setText("");
        taxableCk.setSelected(false);
    }

    
    public void fillPanel(){
        serviceTf.setText(selectedService.getName());
        descriptionTf.setText(selectedService.getDescription());
        priceTf.setText(selectedService.getPrice().toString());
        taxableCk.setSelected(selectedService.isTaxable());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        priceTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        serviceTf = new javax.swing.JTextField();
        descriptionTf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        taxableCk = new javax.swing.JCheckBox();
        buttonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Taxable :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 190, 100, 20);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Service :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 100, 16);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 40, 600, 10);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Transaction Info");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 16, 290, 16);
        jPanel1.add(priceTf);
        priceTf.setBounds(150, 140, 270, 24);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Description :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 110, 100, 16);
        jPanel1.add(serviceTf);
        serviceTf.setBounds(150, 60, 270, 24);
        jPanel1.add(descriptionTf);
        descriptionTf.setBounds(150, 100, 270, 24);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Price :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 150, 100, 16);
        jPanel1.add(taxableCk);
        taxableCk.setBounds(150, 184, 24, 30);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(10, 45));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-pressed.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(saveBtn);

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        updateBtn.setBorder(null);
        updateBtn.setBorderPainted(false);
        updateBtn.setContentAreaFilled(false);
        updateBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-pressed.png"))); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(updateBtn);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel-pressed.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelBtn);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if (serviceTf.getText().isEmpty() == false && priceTf.getText().isEmpty() == false) {
            Service product = new Service();
            product.setId(selectedService.getId());
            product.setName(serviceTf.getText());
            product.setDescription(descriptionTf.getText());
            product.setPrice(Double.parseDouble(priceTf.getText()));
            product.setTaxable(taxableCk.isSelected());

            if (database.update(product)) {

                diag.dispose();
                panel.refreshTable();
                new OkayDialogue(null, true, "Service updated successfully");

            } else {
                new OkayDialogue(null, true, "Failed to updated Service");
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:      if(serviceTF.getText().isEmpty() == false && priceTf.getText().isEmpty() == false){
            Service service = new Service();
            service.setName(serviceTf.getText());
            service.setDescription(descriptionTf.getText());
            service.setPrice(Double.parseDouble(priceTf.getText()));
            service.setTaxable(taxableCk.isSelected());
            
            if(database.insert(service)){
                new OkayDialogue(null, true, "Service saved successfully");
                clearPanels();
                panel.refreshTable();
            } else {
                new OkayDialogue(null, true, "Failed to save Service");
            }
            
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        diag.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField descriptionTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField priceTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField serviceTf;
    private javax.swing.JCheckBox taxableCk;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
