/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialoguePanels;

import core.database.DatabaseAccessObject;
import core.general.Branch;
import core.utilities.Session;
import core.utilities.Settings;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author brand
 */
public class SettingsManagement extends javax.swing.JPanel {

    private Session session;
    private Settings settings;
    private ArrayList<Branch> branchesArray = null;
    private DatabaseAccessObject database;
    private DefaultComboBoxModel branchesModel;
    private DefaultComboBoxModel filteredBranchesModel;
    
            
    /**
     * Creates new form TransactionDialogue
     */
    public SettingsManagement(Session session) {
        this.session = session;
        this.settings = session.getSettings();
        this.database = session.getDatabase();
        initComponents();
        setDefaults();
        fillPanel();
        
        enabledState(false);
        saveBtn.setVisible(false);
    }

    private void setDefaults() {
        refreshPanel();
    }

    public void fillPanel(){
        if(branchesArray == null){
            branchesCB.setSelectedItem("<None>");
            payBucAccountTf.setText(settings.getPayBucAccount());
            taxTf.setText(settings.getTax());
            employeeTip.setSelected(settings.getTipService());
            filterByBranchCB.setSelectedItem(settings.getFilterBranches());
        } else {
            branchesCB.setSelectedItem(settings.getDefaultBranch());
            payBucAccountTf.setText(settings.getPayBucAccount());
            taxTf.setText(settings.getTax());
            employeeTip.setSelected(settings.getTipService());
            filterByBranchCB.setSelectedItem(settings.getFilterBranches());
        }
    }

    public void refreshPanel(){
        branchesArray = database.getBranches();
        refreshBranches();
        refreshFilteredBranches();
    }
    
    public void refreshFilteredBranches() {
        if (branchesArray != null && branchesArray.size() > 0) {

            Object[] tmp = new Object[branchesArray.size()+1];

            tmp[0] = "<Show All>";
            
            for (int i = 1; i <= branchesArray.size(); i++) {
                tmp[i] = branchesArray.get(i-1).getName();
            }
            
            filteredBranchesModel = new DefaultComboBoxModel(tmp);
            filterByBranchCB.setModel(filteredBranchesModel);
            filterByBranchCB.repaint();
            filterByBranchCB.validate();

            if(session.getSettings().getFilterBranches().equals("<Show All>") == false){
                filterByBranchCB.setSelectedItem(session.getSettings().getFilterBranches());
            }
            
        } else {
            Object[] tmp = new Object[]{"<None>"};
            filteredBranchesModel = new DefaultComboBoxModel(tmp);
            filterByBranchCB.setModel(filteredBranchesModel);
            filterByBranchCB.repaint();
            filterByBranchCB.validate();
        }
    }

    public void refreshBranches() {
        if (branchesArray != null && branchesArray.size() > 0) {
            
            Object[] tmp = new Object[branchesArray.size()];

            for (int i = 0; i < branchesArray.size(); i++) {
                tmp[i] = branchesArray.get(i).getName();
            }
            branchesModel = new DefaultComboBoxModel(tmp);
            branchesCB.setModel(branchesModel);
            branchesCB.repaint();
            branchesCB.validate();
            
            if(settings.getDefaultBranch().equals("<None>")){
                branchesCB.setSelectedIndex(-1);
            } else {
                branchesCB.setSelectedItem(settings.getDefaultBranch());
            }
            
        } else {

            Object[] tmp = new Object[]{"<None>"};
            branchesModel = new DefaultComboBoxModel(tmp);
            branchesCB.setModel(branchesModel);
            branchesCB.repaint();
            branchesCB.validate();
        }
    }

    public void enabledState(boolean state) {
        branchesCB.setEnabled(state);
        payBucAccountTf.setEnabled(state);
        taxTf.setEnabled(state);
        filterByBranchCB.setEnabled(state);
        employeeTip.setEnabled(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payBucAccountTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        branchesCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        taxTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        filterByBranchCB = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        employeeTip = new javax.swing.JCheckBox();
        buttonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Default Branch :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 100, 16);
        jPanel1.add(payBucAccountTf);
        payBucAccountTf.setBounds(130, 50, 270, 24);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PayBuc Account :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 60, 100, 16);

        branchesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(branchesCB);
        branchesCB.setBounds(130, 10, 270, 26);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tax % :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 100, 100, 16);
        jPanel1.add(taxTf);
        taxTf.setBounds(130, 90, 270, 24);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Filter By Branch :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 180, 100, 16);

        filterByBranchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(filterByBranchCB);
        filterByBranchCB.setBounds(130, 170, 270, 26);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Employee Tip :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 140, 100, 16);
        jPanel1.add(employeeTip);
        employeeTip.setBounds(130, 130, 270, 24);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(10, 45));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-pressed.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(saveBtn);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-pressed.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(editBtn);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        settings.setBayBucAccount(payBucAccountTf.getText());
        settings.setDefaultBranch(branchesCB.getSelectedItem().toString());
        settings.setTax(taxTf.getText());
        settings.setTipService(employeeTip.isSelected());
        settings.setFilterBranches(filterByBranchCB.getSelectedItem().toString());
        settings.saveSettings();
        
        enabledState(false);
        saveBtn.setVisible(false);
        editBtn.setVisible(true);
        new OkayDialogue(null, true, "Settings Saved.");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        saveBtn.setVisible(true);
        editBtn.setVisible(false);
        enabledState(true);
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchesCB;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JCheckBox employeeTip;
    private javax.swing.JComboBox<String> filterByBranchCB;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField payBucAccountTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField taxTf;
    // End of variables declaration//GEN-END:variables



}
