/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialoguePanels;

import core.database.DatabaseAccessObject;
import core.general.Branch;
import core.utilities.Session;
import core.utilities.Settings;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author brand
 */
public class SettingsManagement extends javax.swing.JPanel {

    private Session session;
    private Settings settings;
    private ArrayList<Branch> branchesArray = null;
    private DatabaseAccessObject database;
    private DefaultComboBoxModel branchesModel;
    private DefaultComboBoxModel filteredBranchesModel;
    private Dialogue diag;
    
            
    /**
     * Creates new form TransactionDialogue
     */
    public SettingsManagement(Session session) {
        this.session = session;
        this.settings = session.getSettings();
        this.database = session.getDatabase();
        initComponents();
        setDefaults();
        fillPanel();
        
        enabledState(false);
        saveBtn.setVisible(false);
    }

    private void setDefaults() {
        refreshPanel();
    }

    public void fillPanel(){
        if(branchesArray == null){
            branchesCB.setSelectedItem("<None>");
            payBucAccountTf.setText(settings.getPayBucAccount());
            taxTf.setText(settings.getTax());
            filterByBranchCB.setSelectedItem(settings.getFilterBranches());
        } else {
            branchesCB.setSelectedItem(settings.getDefaultBranch());
            payBucAccountTf.setText(settings.getPayBucAccount());
            taxTf.setText(settings.getTax());
            filterByBranchCB.setSelectedItem(settings.getFilterBranches());
        }
    }

    public void refreshPanel(){
        branchesArray = database.getBranches();
        refreshBranches();
        refreshFilteredBranches();
    }
    
    public void refreshFilteredBranches() {
        if (branchesArray != null && branchesArray.size() > 0) {

            Object[] tmp = new Object[branchesArray.size()+1];

            tmp[0] = "<Show All>";
            
            for (int i = 1; i <= branchesArray.size(); i++) {
                tmp[i] = branchesArray.get(i-1).getName();
            }
            
            filteredBranchesModel = new DefaultComboBoxModel(tmp);
            filterByBranchCB.setModel(filteredBranchesModel);
            filterByBranchCB.repaint();
            filterByBranchCB.validate();

            if(session.getSettings().getFilterBranches().equals("<Show All>") == false){
                filterByBranchCB.setSelectedItem(session.getSettings().getFilterBranches());
            }
            
        } else {
            Object[] tmp = new Object[]{"Show All"};
            branchesModel = new DefaultComboBoxModel(tmp);
            branchesCB.setModel(branchesModel);
            branchesCB.repaint();
            branchesCB.validate();
        }
    }

    public void refreshBranches() {
        if (branchesArray != null && branchesArray.size() > 0) {
            
            Object[] tmp = new Object[branchesArray.size()];

            for (int i = 0; i < branchesArray.size(); i++) {
                tmp[i] = branchesArray.get(i).getName();
            }
            branchesModel = new DefaultComboBoxModel(tmp);
            branchesCB.setModel(branchesModel);
            branchesCB.repaint();
            branchesCB.validate();
            
            if(settings.getDefaultBranch().equals("<None>")){
                branchesCB.setSelectedIndex(-1);
            } else {
                branchesCB.setSelectedItem(settings.getDefaultBranch());
            }
            
        } else {

            Object[] tmp = new Object[]{"<None>"};
            branchesModel = new DefaultComboBoxModel(tmp);
            branchesCB.setModel(branchesModel);
            branchesCB.repaint();
            branchesCB.validate();
        }
    }

    public void enabledState(boolean state) {
        branchesCB.setEnabled(state);
        payBucAccountTf.setEnabled(state);
        taxTf.setEnabled(state);
        filterByBranchCB.setEnabled(state);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        payBucAccountTf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        branchesCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        taxTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        filterByBranchCB = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        buttonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Default Branch :");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PayBuc Account :");

        branchesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tax % :");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Filter By Branch :");

        filterByBranchCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Software Settings");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(branchesCB, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payBucAccountTf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taxTf, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filterByBranchCB, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(branchesCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payBucAccountTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taxTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterByBranchCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(10, 45));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-pressed.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(saveBtn);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit.png"))); // NOI18N
        editBtn.setBorder(null);
        editBtn.setBorderPainted(false);
        editBtn.setContentAreaFilled(false);
        editBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-pressed.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(editBtn);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel-pressed.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelBtn);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        settings.setBayBucAccount(payBucAccountTf.getText());
        settings.setDefaultBranch(branchesCB.getSelectedItem().toString());
        settings.setTax(taxTf.getText());
        settings.setFilterBranches(filterByBranchCB.getSelectedItem().toString());
        settings.saveSettings();
        
        enabledState(false);
        saveBtn.setVisible(false);
        editBtn.setVisible(true);
        new OkayDialogue(null, true, "Settings Saved.");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        saveBtn.setVisible(true);
        editBtn.setVisible(false);
        enabledState(true);
    }//GEN-LAST:event_editBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.diag.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> branchesCB;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox<String> filterByBranchCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField payBucAccountTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField taxTf;
    // End of variables declaration//GEN-END:variables

    void setDialogue(Dialogue aThis) {
        this.diag = aThis;
    }



}
