/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.dialoguePanels;

import core.database.DatabaseAccessObject;
import core.enums.TableStatus;
import core.general.Occupation; 
import core.general.Table;
import core.utilities.Session;
import gui.services.OccupationsManagementPanel; 
import gui.services.TablesManagementPanel;


/**
 * @author brand
 */
public class TablesDialogue extends javax.swing.JPanel {
    private Session session ;
    private DatabaseAccessObject database;
    private TablesManagementPanel panel;
    private Dialogue diag;
    private Table selectedTable = null;
    
    /**
     * Creates new form TransactionDialogue
     */
    public TablesDialogue(Session session, TablesManagementPanel panel) {
        this.session = session;
        this.database = session.getDatabase();
        this.panel = panel;
        
        initComponents();
        setDefaults();
        updateBtn.setVisible(false);
    }
    

    public TablesDialogue(Session session, TablesManagementPanel panel, Table table) {
        this.session = session;
        this.database = session.getDatabase();
        this.panel = panel;
        this.selectedTable = table;
        
        initComponents();
        setDefaults();
        fillPanel();
        saveBtn.setVisible(false);
    }
    
    public void fillPanel(){
        titleTf.setText(selectedTable.getTableName());
        tableStatus.setSelectedItem(selectedTable.getTableStatus());
    }
    
    
    void setDialogue(Dialogue dialogue) {
        diag = dialogue;
    }
    
    private void setDefaults() {
    }

    public void clearPanels(){
        titleTf.setText("");
        tableStatus.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        titleTf = new javax.swing.JTextField();
        tableStatus = new javax.swing.JComboBox<>(TableStatus.values());
        buttonsPanel = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Name/ Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 70, 100, 16);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(20, 40, 600, 10);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Table Info");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 16, 290, 16);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Table Status :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 110, 100, 16);
        jPanel1.add(titleTf);
        titleTf.setBounds(150, 60, 270, 24);

        jPanel1.add(tableStatus);
        tableStatus.setBounds(150, 110, 270, 26);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        buttonsPanel.setPreferredSize(new java.awt.Dimension(10, 45));
        buttonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-pressed.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(saveBtn);

        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update.png"))); // NOI18N
        updateBtn.setBorder(null);
        updateBtn.setBorderPainted(false);
        updateBtn.setContentAreaFilled(false);
        updateBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update-pressed.png"))); // NOI18N
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(updateBtn);

        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel-pressed.png"))); // NOI18N
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        buttonsPanel.add(cancelBtn);

        add(buttonsPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(titleTf.getText().isEmpty() == false && tableStatus.getSelectedIndex() > -1){
            Table table = new Table();
            table.setTableName(titleTf.getText());
            table.setTableStatus((TableStatus) tableStatus.getSelectedItem()); 
            
            if(database.insert(table)){
                new OkayDialogue(null, true, "Table saved successfully");
                clearPanels();
                panel.refreshTable();
            } else {
                new OkayDialogue(null, true, "Failed to save Table");
            }
            
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(titleTf.getText().isEmpty() == false && tableStatus.getSelectedIndex() > -1){
            Table table = new Table();
            table.setId(selectedTable.getId());
            table.setTableName(titleTf.getText());
            table.setTableStatus((TableStatus) tableStatus.getSelectedItem()); 
            
            if (database.update(table)) {
                new OkayDialogue(null, true, "Table updated successfully");
                panel.refreshTable();
                
            } else {
                new OkayDialogue(null, true, "Failed to update Table");
            }

        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.diag.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox<TableStatus> tableStatus;
    private javax.swing.JTextField titleTf;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

}
