/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.cards;

/**
 *
 * @author brand
 */
public class Card extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */
    public Card(String Title) {
        initComponents();
        title.setText(Title);
        
    }
    
    public void setAmountValue(String value){
        amount.setText(value);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(315, 180));
        setPreferredSize(new java.awt.Dimension(315, 180));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setMinimumSize(new java.awt.Dimension(35, 19));
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 16));
        jPanel2.add(jLabel3, java.awt.BorderLayout.LINE_END);

        amount.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        amount.setText("  R9000.00");
        jPanel2.add(amount, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);

        title.setBackground(new java.awt.Color(0, 186, 186));
        title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("    Transactions");
        title.setOpaque(true);
        title.setPreferredSize(new java.awt.Dimension(41, 30));
        add(title, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
