/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.services;

import core.utilities.Session;
import gui.cards.Card;

/**
 *
 * @author brand
 */
public class DashboardPanel extends javax.swing.JPanel {

    private Session session;
    private Card transCard = new Card(" Transactions Sales");
    private Card transCard1 = new Card(" Sales");
    private Card transCard2 = new Card(" Weekly Sales");
    private Card transCard3 = new Card(" Todays Sales");
    private Card transCard4 = new Card(" Total Transactions");
    private Card transCard5 = new Card("");
    private Card transCard6 = new Card("");
    
    /**
     * Creates new form Services
     */
    public DashboardPanel(Session session) {
        this.session = session;
        initComponents();
        cardsPanel.add(transCard);
        cardsPanel.add(transCard1);
        cardsPanel.add(transCard2);
        cardsPanel.add(transCard3);
        cardsPanel.add(transCard4);
        cardsPanel.add(transCard5);
        cardsPanel.add(transCard6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        bottomButtonsPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainCenter = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardsPanel = new javax.swing.JPanel();
        bottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1058, 720));
        setLayout(new java.awt.BorderLayout());

        main.setLayout(new java.awt.BorderLayout());

        bottomButtonsPanel.setBackground(new java.awt.Color(227, 227, 227));
        bottomButtonsPanel.setPreferredSize(new java.awt.Dimension(1058, 60));
        bottomButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 10));

        jButton1.setText("jButton1");
        bottomButtonsPanel.add(jButton1);

        main.add(bottomButtonsPanel, java.awt.BorderLayout.PAGE_END);

        jPanel1.setBackground(new java.awt.Color(227, 227, 227));
        jPanel1.setPreferredSize(new java.awt.Dimension(20, 589));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        main.add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(227, 227, 227));
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 589));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        main.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(227, 227, 227));
        jPanel3.setPreferredSize(new java.awt.Dimension(959, 50));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(815, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        mainCenter.setLayout(new java.awt.GridLayout(2, 0));

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(227, 227, 227));
        jLabel2.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Latest Transactions");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(61, 45));
        top.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        cardsPanel.setBackground(new java.awt.Color(227, 227, 227));
        cardsPanel.setLayout(new java.awt.GridLayout(2, 4, 5, 5));
        top.add(cardsPanel, java.awt.BorderLayout.CENTER);

        mainCenter.add(top);

        bottom.setBackground(new java.awt.Color(227, 227, 227));
        bottom.setLayout(new java.awt.BorderLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Description", "Employee", "Client Name", "Client Cell", "Payment", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mainCenter.add(bottom);

        main.add(mainCenter, java.awt.BorderLayout.CENTER);

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottom;
    private javax.swing.JPanel bottomButtonsPanel;
    private javax.swing.JPanel cardsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel mainCenter;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
